### ISSUE TITLE
memory and remote access issues

### ISSUE THREAD

**Issue by satra** [ome/ome2024-ngff-challenge#83]
using main branch.

i'm runnning the following trying write out a 32G (blosc-zstd compressed size) zarr file to a v3 with a single shard.

` ome2024-ngff-challenge resave --cc-by --output-shards 1,1,2048,2048,30208 test.zarr  tmp.zarr`

the memory keeps increasing and the job gets killed when it runs out of pod memory (96G).

file is publicly available at: https://dandiarchive.s3.amazonaws.com/zarr/acfaff07-8d4d-4fc1-adce-c769579c5c61/

and trying to read from the remote url and writing locally errors out as below:

<details> <summary> Error from remote run </summary>
$ ome2024-ngff-challenge resave --cc-by         --input-bucket=dandiarchive         --input-endpoint=https://dandiarchive.s3.amazonaws.com         --input-anon         --input-region us-east-2         zarr/acfaff07-8d4d-4fc1-adce-c769579c5c61         tmp.zarr

```python
Traceback (most recent call last):
  File "/home/jovyan/conda-envs/zarrv3/lib/python3.11/site-packages/zarr/api/asynchronous.py", line 523, in open_group
    return await AsyncGroup.open(store_path, zarr_format=zarr_format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda-envs/zarrv3/lib/python3.11/site-packages/zarr/group.py", line 148, in open
    raise FileNotFoundError(store_path)
FileNotFoundError: Remote fsspec store: S3FileSystem , dandiarchive/zarr/acfaff07-8d4d-4fc1-adce-c769579c5c61

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jovyan/conda-envs/zarrv3/bin/ome2024-ngff-challenge", line 8, in <module>
    sys.exit(dispatch())
             ^^^^^^^^^^
  File "/home/jovyan/conda-envs/zarrv3/lib/python3.11/site-packages/ome2024_ngff_challenge/__init__.py", line 36, in dispatch
    return ns.func(ns)
           ^^^^^^^^^^^
  File "/home/jovyan/conda-envs/zarrv3/lib/python3.11/site-packages/ome2024_ngff_challenge/resave.py", line 424, in main
    input_config.open_group()
  File "/home/jovyan/conda-envs/zarrv3/lib/python3.11/site-packages/ome2024_ngff_challenge/utils.py", line 331, in open_group
    self.zr_group = zarr.open_group(store=self.zr_store, zarr_format=2)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda-envs/zarrv3/lib/python3.11/site-packages/zarr/api/synchronous.py", line 175, in open_group
    sync(
  File "/home/jovyan/conda-envs/zarrv3/lib/python3.11/site-packages/zarr/sync.py", line 92, in sync
    raise return_result
  File "/home/jovyan/conda-envs/zarrv3/lib/python3.11/site-packages/zarr/sync.py", line 51, in _runner
    return await coro
           ^^^^^^^^^^
  File "/home/jovyan/conda-envs/zarrv3/lib/python3.11/site-packages/zarr/api/asynchronous.py", line 525, in open_group
    return await AsyncGroup.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/conda-envs/zarrv3/lib/python3.11/site-packages/zarr/abc/store.py", line 203, in set_or_delete
    await byte_setter.set(value)
  File "/home/jovyan/conda-envs/zarrv3/lib/python3.11/site-packages/zarr/store/core.py", line 40, in set
    await self.store.set(self.path, value)
  File "/home/jovyan/conda-envs/zarrv3/lib/python3.11/site-packages/zarr/store/remote.py", line 120, in set
    self._check_writable()
  File "/home/jovyan/conda-envs/zarrv3/lib/python3.11/site-packages/zarr/abc/store.py", line 29, in _check_writable
    raise ValueError("store mode does not support writing")
ValueError: store mode does not support writing
```
</details>

cc: @balbasty

**Comment by joshmoore** [comment]
Thanks for giving it a try, @satra. I'm on the road and so will hold off on downloading via hotel wifi :wink: Could you try lowering the parallelism from the default of 16, e.g. `--output-threads=4` or lower and see how you fair. 

As for the S3 error, my first instinct would be for us to try bumping the zarr-python version from 3.0.0a0 to 3.0.0b2 in case you want to give that a try. That will require some local changes though, e.g.,

```
-        store_class = zarr.store.LocalStore
+        store_class = zarr.storage.local.LocalStore
```

which you may or may not want to dive into.

**Comment by satra** [comment]
unfortunately setting `--output-threads=1` even doesn't work. i tried a few low numbers :) perhaps its trying to read all of the data into memory before writing.

**Comment by joshmoore** [comment]
> i tried a few low numbers :)

:) :+1:

> perhaps its trying to read all of the data into memory before writing.

That's what it *sounds* like but then I think fewer people would have completed the challenge. If no one has another sense, I'll dig in once I'm back at a desktop.

**Comment by will-moore** [comment]
I think it may try to read all the data for a shard into memory at once? Smaller shard size might help.
If you look at all the challenge data at https://ome.github.io/ome2024-ngff-challenge/ and sort by shard size, only 1 image has a bigger shard size than `2048 * 2048 * 30208`.

**Comment by satra** [comment]
@will-moore - that was it. i'll look into the code to see if we can optimize this a bit.
